<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Política de privacidad · Gestión Fábrica</title>@vite(['resources/css/app.css'])</head>
<body class="bg-gray-100 text-gray-800"><main class="max-w-4xl mx-auto px-5 py-10"><div class="bg-white border rounded-2xl p-6 md:p-10 shadow-sm space-y-6">
<div><h1 class="text-3xl font-bold">Política de privacidad</h1><p class="mt-3 text-gray-600">Esta política describe cómo Gestión Fábrica trata los datos personales y operativos necesarios para prestar el servicio.</p></div>
<section class="space-y-2"><h2 class="text-xl font-semibold">1. Datos tratados</h2><p>Datos de usuarios autorizados (nombre, email o teléfono, rol y estado), identificador de Telegram y mensajes operativos, información de inventario, compras, producción, proveedores, máquinas y ventas, además de datos técnicos de seguridad como IP, agente de usuario, accesos y eventos.</p><p>En Mercado Pago se guardan identificadores y metadatos necesarios para verificar y conciliar operaciones. El sistema no necesita almacenar números de tarjeta ni credenciales bancarias del comprador.</p></section>
<section class="space-y-2"><h2 class="text-xl font-semibold">2. Finalidades</h2><p>Operar la gestión interna, controlar stock y producción, responder consultas autorizadas, registrar ventas de máquinas, calcular comisiones, mantener trazabilidad, prevenir abuso y diagnosticar incidentes.</p></section>
<section class="space-y-2"><h2 class="text-xl font-semibold">3. Proveedores e integraciones</h2><p>Cuando una función lo requiere pueden intervenir el alojamiento de la aplicación, Telegram, Google/Gemini y Mercado Pago. Se envía a cada servicio sólo la información necesaria para la función correspondiente.</p></section>
<section class="space-y-2"><h2 class="text-xl font-semibold">4. Seguridad y acceso</h2><p>El panel requiere autenticación y limita funciones por rol. Los encargados sólo pueden operar inventario; la administración queda reservada a dueños. Las credenciales OAuth de Mercado Pago se almacenan cifradas y los cambios de stock quedan en un historial.</p></section>
<section class="space-y-2"><h2 class="text-xl font-semibold">5. Conservación</h2><p>La información se conserva el tiempo necesario para operación, trazabilidad, seguridad y obligaciones comerciales o legales aplicables.</p></section>
<section class="space-y-2"><h2 class="text-xl font-semibold">6. Consultas sobre datos</h2><p>Las solicitudes de acceso, corrección o eliminación que correspondan deben dirigirse al responsable de la empresa que utiliza el sistema.</p><p class="font-medium">{{ config('legal.contact_name') }}@if(config('legal.contact_email')) · {{ config('legal.contact_email') }}@endif</p></section>
<div class="pt-4 border-t flex gap-4 text-sm"><a href="{{ route('legal.cookies') }}" class="text-blue-700 hover:underline">Política de cookies</a><a href="{{ route('login') }}" class="text-blue-700 hover:underline">Volver al acceso</a></div>
</div></main></body></html>
